### ISSUE TITLE
Problems after update to FireFox 108

### ISSUE THREAD

**Issue by JohnyP36** [BPower0036/UserChrome#3]
Line after `Extensie...` is halfway the icon.

![afbeelding](https://user-images.githubusercontent.com/81161435/207556680-9618676d-0954-45f7-875c-7e1963bec1b4.png)

Icon is repeated when clicking on `Website-informatie`
![afbeelding](https://user-images.githubusercontent.com/81161435/207557010-f76f1f66-727d-4b1f-97c4-eee231dabd65.png)
![afbeelding](https://user-images.githubusercontent.com/81161435/207557047-580c15db-73f6-4c51-9082-1a3d8157367f.png)

**Comment by Nomes77** [comment]
I will look at it when my browser is restarted, maybe tomorrow.
If there a more issue you can let it know me here.

**Comment by JohnyP36** [comment]
- The "Windscribe" icon is not removed if `zavety` enabled, because it is not `toolbarbutton` but **`toolbaritem`**.
- Popup menu's are bigger now. (uBO, Windscribe, Multi-Account Container)
- Extension menu should maybe made smaller, because of extra icons at the right.

**Comment by Nomes77** [comment]
![afbeelding](https://user-images.githubusercontent.com/80090789/207571171-bb404986-6b4d-4905-989f-983680f68a6a.png)
